name: Scrape Google Images

on:
  workflow_dispatch:  # Jalankan workflow secara manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' 

    - name: Install dependencies
      run: npm install scrape-google-images

    - name: Run scraper
      run: node index.js
